### ISSUE TITLE
bug反馈与功能建议

### ISSUE THREAD

**Issue by pin189** [hupo376787/WeiboAlbumDownloader#1]
使用效果：很好用。方便快捷。
功能建议：可以添加一个功能吗？自定义下载文件名。
bug反馈：如果相册页面一直加载中，数据源选择weibo.com是不是不行。实测 uid=3476825950 如下图，数据源选择weibo.com报错。
![专辑页面](https://github.com/hupo376787/WeiboAlbumDownloader/assets/79697022/502a6dd0-88c6-403a-8af8-7e7180f9a5c0)
![软件页面](https://github.com/hupo376787/WeiboAlbumDownloader/assets/79697022/7778a126-efbe-4bba-8c63-9310a2f28852)

**Comment by pin189** [comment]
更新：bug原因-数据源未选择weibo.com。
如果相册专辑页面一直加载中，数据源选择weibo.com是不是不行。
实测 uid=5843630243 如下图，数据源选择weibo.com报错。
![软件页面](https://github.com/hupo376787/WeiboAlbumDownloader/assets/79697022/21f0e6f4-98d7-4f35-a577-bc801f0391f8)
![专辑页面](https://github.com/hupo376787/WeiboAlbumDownloader/assets/79697022/059c80f9-1e26-48b3-b50d-3c4629428e56)

**Comment by hupo376787** [comment]
还真是的，这个用户的相册再请求消息的时候，直接返回了`504 Gateway Time-out`，我再摸摸微薄的规律
