### ISSUE TITLE
下载时出现错误，无法继续。

### ISSUE THREAD

**Issue by ilikeulinux** [hupo376787/WeiboAlbumDownloader#3]
![QQ截图20240903103927](https://github.com/user-attachments/assets/f513fcab-8710-49a9-8e20-fafdd43772f9)

**Comment by hupo376787** [comment]
看错误提示，应该是下载完了。发送通知的时候出错

**Comment by ilikeulinux** [comment]
> 看错误提示，应该是下载完了。发送通知的时候出错

您的工具非常好用
