### ISSUE TITLE
批量下载怎么使用

### ISSUE THREAD

**Issue by oliver1232123** [hupo376787/WeiboAlbumDownloader#7]
**Bug描述**
简单描述一下bug，最好附带uid，方便具体排查原因。

**如何复现**
复现步骤：
1. 
2. 
3. 

**截图**
错误信息截图

**软件版本:**
 - 版本 [e.g. 22]

**额外描述**
额外描述信息

**Comment by hupo376787** [comment]
现在有点问题，稍等几天，我修复一下

**Comment by hupo376787** [comment]
已完成批量下载，请下载4.1版本
